### PR TITLE
Remove invalid link

### PR DESCRIPTION
**Pull request by malyborky**

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Hi, thanks! I actually found the video here: https://www.reddit.com/r/JustinY/comments/93u8rj/justiny_is_domics_introvert/

I am not able to download it correctly though and I am afraid that it will be removed as well. Do you think it makes sense to replace it instead of removing it?

**Comment by malyborky** [comment]
Hi, yes, definitely worth replacing.
I expect it's not going to be replaced so soon as it is not on YT anymore.

**Comment by mrtnzlml** [comment]
OK - will replace (even though the Reddit page is a bit odd 😬). However, do you know how to download the video stream correctly? I tried but no luck. I think at least the first half of the video is really very well explained and I would love to preserve it...

**Comment by mrtnzlml** [comment]
Muchas gracias @malyborky! :)

**Comment by malyborky** [comment]
You can download it from reddit,
https://redv.co/?url=r/JustinY/comments/93u8rj/justiny_is_domics_introvert/
but you have to download audio and video separately as reddit splits it (you can then merge it in a video editor).

**Pull request merged**
